<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\View\View;
use Illuminate\Support\Facades\Http;

class AdminController extends Controller
{

    public function show(): View
{
    try {
        $apiStudents = $this->apiUrl . 'students';
        $apiCompanies = $this->apiUrl . 'companies';
        $apiLogs = $this->apiUrl . 'admin/logs';

        $response = Http::get($apiStudents);
        
        $students = $response->json('data');

        //Second response for companies
        $response = Http::get($apiCompanies);
        
        $companies = $response->json('data');

        $appointments = $this->getAppointments();   
        $connections = $this->getConnections();
        //Final response for logs
        $response = Http::get($apiLogs);
        $logs = $response->json('data');

        $logs = $logs['data'];
        //Replace target id with target name
        //code generated by github copilot
        foreach ($logs as &$log) {
            $id = $log['actor'];
            if ($log['actor'] === 'Student') {
                $student = collect($students)->firstWhere('id', $id);
                $log['target_id'] = $student ? $student['first_name'] . ' ' . $student['last_name'] : 'Onbekende student';
            } elseif ($log['actor'] === 'Company') {
                $company = collect($companies)->firstWhere('id', $id);
                $log['actor'] = $company ? $company['name'] : 'Onbekend bedrijf';
            }
            elseif ($log['target_type'] === 'Admin') {
                $log['actor'] = 'Steve';
            }
            else {
                $log['actor'] = 'Onbekend doel';
            }
            //Set date to better format
            $log['date'] = substr($log['timestamp'], 8, 2) . "/" . substr($log['timestamp'], 5, 2) . "/" . substr($log['timestamp'], 0, 4);
            $log['time'] = substr($log['timestamp'], 11, 2) . "u" . substr($log['timestamp'], 14, 2);
            //Set target_type to dutch
            if ($log['target_type'] === 'Student') {
                $log['target_type'] = 'Student';
            } elseif ($log['target_type'] === 'Company') {
                $log['target_type'] = 'Bedrijf';
            } elseif ($log['target_type'] === 'Admin') {
                $log['target_type'] = 'Beheerder';
            } else {
                $log['target_type'] = 'Onbekend type';
            }
        }
        
        return view('/admin/admin', [
            'students' => $students, 
            'companies' => $companies,
            'appointments' => $appointments,
            'connections' => $connections,
            'logs' => $logs
    ]);
    } catch (\Exception $e) {
        dd('failure: ' . $e->getMessage());
        return view('voorbeeld.index', ['error' => 'Er is een fout opgetreden', 'students' => []]);
    }
}
#Code created by copilot
#Function to store students the admin created
public function storeS(Request $request)
    {
        try {
            $validated = $request->validate([
            'firstName' => 'required|string|max:255',
            'lastName' => 'required|string|max:255',
            'email' => 'required|email|max:255',
            'graduation_track' => 'required|string|max:255',
            'study_direction' => 'required|string|max:255',
            'password1' => 'required|string|min:8',
            'password2' => 'required|same:password1'
            ]);
        } catch (\Exception $e) {
            return redirect()->back()->with('error', 'Validatie mislukt: ' . $e->getMessage());
        }
        

    // Prepare data for API (use password2 as password)
    $data = [
        'firstName' => $validated['firstName'],
        'lastName' => $validated['lastName'],
        'email' => $validated['email'],
        'password' => $validated['password2'],
        'graduation_track' => $validated['graduation_track'],
        'study_direction' => $validated['study_direction'],
        'interests' => 'Ik heb interesse in...',
        'job_preferences' => 'Ik heb voorkeuren voor...',
        'cv' => 'cv.pdf',
        'profile_complete' => '0',
    ];

try {
    $response = Http::post($this->apiUrl . 'students', $data);

    if ($response->successful()) {
        return redirect()->back()->with('success', 'Student succesvol toegevoegd!');
    } else {
        // Voeg de response body toe aan de foutmelding voor debugging
        return redirect()->back()->with('error', 'Fout bij toevoegen van Student: ' . $response->body());
    }
} catch (\Exception $e) {
    return redirect()->back()->with('error', 'Er is een fout opgetreden: ' . $e->getMessage());
}
    }


    //
    protected function getAppointments() {
        $response = Http::get($this->appointmentApiUrl);

        $data = $response->json('data');
        foreach ($data as &$appointment) {
            //translate student and company id to names
            $appointment['student_id'] = $this->translateStudent($appointment['student_id']);

            
            $appointment['company_id'] = $this->translateCompany($appointment['company_id']);
        }
        return $data;
    }

    protected function getConnections() {
        $response = Http::get($this->connectionsApiUrl);

        $data = $response->json('data');
        foreach ($data as &$connection) {
            //translate student and company id to names
            $connection['student_id'] = $this->translateStudent($connection['student_id']);
            $connection['company_id'] = $this->translateCompany($connection['company_id']);

            if ($connection['status'] === '1') {
                $connection['status'] = 'Actief';
            } 
            else {
                $connection['status'] = 'Afgesloten';
            }
        }
        return $data;
    }

}
