<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\View\View;
use Illuminate\Support\Facades\Http;


abstract class Controller
{
    // API URLs for appointments, students, and companies
    protected $appointmentApiUrl = 'http://10.2.160.208/api/appointments';
    protected string $studentsApiUrl = 'http://10.2.160.208/api/students';
    protected string $companiesApiUrl = 'http://10.2.160.208/api/companies';

    #bottom functions generated by github copilot. Use a student or company object to get the name of the student or company
    protected function translateStudent($id)
    {
        
        $student = Http::get("{$this->studentsApiUrl}/{$id}")->json('data');

        if (isset($student['first_name']) && isset($student['last_name'])) {
                $id = $student['first_name'] . ' ' . $student['last_name'];
            } else {
                $id = 'Onbekende student';
            }
            return $id;
    }
    protected function translateCompany($id)
    {
        $company = Http::get("{$this->companiesApiUrl}/{$id}")->json('data');
        if (isset($company['name'])) {
            $id = $company['name'];
        } else {
            $id = 'Onbekend bedrijf';
        }
        return $id;
    }
}
